# Generated by Django 5.1.6 on 2025-04-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='email',
            new_name='restaurant_email',
        ),
    ]
