# Generated by Django 5.1.6 on 2025-05-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_name_restaurant_restaurant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner',
            new_name='user_id',
        ),
    ]
