# Generated by Django 5.1.6 on 2025-05-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_owner_restaurant_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='user_id',
            new_name='owner',
        ),
    ]
