# Generated by Django 5.1.6 on 2025-05-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_user_id_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='slug',
        ),
    ]
