# Generated by Django 5.1.6 on 2025-05-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
