# Generated by Django 5.1.6 on 2025-05-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_user_deliveryagentprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagentprofile',
            old_name='user_id',
            new_name='agent',
        ),
    ]
