# Generated by Django 5.1.6 on 2025-05-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_user_customerprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user_id',
            new_name='customer',
        ),
    ]
